### ISSUE TITLE
`locale` doesn't seem to be working

### ISSUE THREAD

**Issue by aborruso** [posit-dev/great-tables#121]
## Description

I have dataframe schema:

```
Cat         object
Field 1     object
Field 2      int64
Field 3    float64
dtype: object
```

I have the float `5789.56` in `Field 3`, I render the table using `GT(table,locale="it-IT",rowname_col="Cat")`, but in the output I do not have the `,` ad decimal separator, I do not have `5789,56`.

## Reproducible example

I have all in this [small repo](https://github.com/aborruso/sample). This is the [rendered table](https://aborruso.github.io/sample/gt.html#rendered-by-gt), and this is the [source file](https://github.com/aborruso/sample/blob/main/gt.qmd).

## Expected result

To have the `,` as decimal separator.

## Development environment

-   Operating System: debian 11
-   **great\_tables** Version: 0.1.5
-   Quarto: 1.4.536

**Comment by rich-iannone** [comment]
To solve this you have to explicit format values with a `fmt_*()` method. In your example code you were assigning a locale in the `GT` class but not using a formatter. Instead, do this (I'm using the `exibble` dataset because I don't have your data)

```py
from great_tables import GT, exibble

GT(exibble, locale="it-IT").fmt_number(columns="num")
```

or

```py
GT(exibble).fmt_number(columns="num", locale = "it-IT")
```

and you'll get the intended formatting (take a look at the formatted values in the `num` column):

<img width="887" alt="exibble-format-number" src="https://github.com/posit-dev/great-tables/assets/5612024/0459600e-536b-4149-aa6b-b38677a41e88">

The first approach is better since you might use several `fmt_*()` methods and you won't need to always specify the locale. By the way, the locale `"it"` also works (`"it-IT"` == `"it"`).

**Comment by aborruso** [comment]
thank you @rich-iannone 

However, I did not understand if there is a syntax to say to apply `local="it-IT"` to all numeric columns. Without hard-coding all the column names.
