### ISSUE TITLE
Add python 3.8 support; 

### ISSUE THREAD

**Issue by schloerke** [posit-dev/great-tables#383]
`great-tables` should support the same versions of supported python versions as in https://devguide.python.org/versions/#supported-versions

Today, this is python 3.8+ (not python 3.9+).

**Comment by machow** [comment]
Hey--we are currently following [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table), but will likely switch to the [devguide](https://devguide.python.org/versions/#supported-versions) in the future (since it seems like Polars is also following this).

Since the EOL of 3.8 is close, it seems okay to close for now, and use the devguide for future EOL guidance (e.g. on deciding when to drop 3.9). @rich-iannone, WDYT?

**Comment by schloerke** [comment]
If py-shiny is adopting `great-tables` within a couple weeks for data frame usage, I'd like to advocate for 3.8 support in `great-tables`.

**Comment by machow** [comment]
Are you planning to add `great-tables` as a hard dependency? If shiny is just adding the ability to handle a GT object, then at the point it receives one, you'll know the person is on python 3.9+.

**Comment by jrycw** [comment]
I'll close this issue as Python 3.8 has reached its end of life on 2024-10-07, according to the [dev guide](https://devguide.python.org/versions/#unsupported-versions).
